name: msfoole
version: 1.0.0
description: 基于swoole4的简易微服务API框架
environments:
  MSFOOLE__HOST: "0.0.0.0"
  MSFOOLE__PORT: 9111
  MSFOOLE__SSL: false
  MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole-core/src/
  MSFOOLE__MONITOR__INTERVAL: 10
  MSFOOLE__MACHINE__REGPORT: 9222
  MSFOOLE__MACHINE__ROBOTKEY: regMachine
  MSFOOLE__CALL__PORT: 9333
  MSFOOLE__CHANNEL__CAPACITY: 100
  MSFOOLE__OPTION__WORKER_NUM: 1
  MSFOOLE__OPTION__MAX_REQUEST: 10000
  MSFOOLE__OPTION__MAX_CONN: 10000
  MSFOOLE__OPTION__DAEMONIZE: false
  MSFOOLE__OPTION__LOG_LEVEL: 0
  MSFOOLE__OPTION__LOG_FILE: msfoole.log
  MSFOOLE__OPTION__REQUEST_SLOWLOG_FILE: trace.log
  MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 1
  MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 120
  MSFOOLE__OPTION__OPEN_HTTP2_PROTOCOL: false
  MSFOOLE__OPTION__RELOAD_ASYNC: false
  MSFOOLE__OPTION__ENABLE_COROUTINE: true
  MSFOOLE__OPTION__MAX_COROUTINE: 3000
  CACHE__DEFAULT__DRIVER: redis
  CAHCE__DEFAULT__PREFIX: "cache:"
  CACHE__DEFAULT__EXPIRE: 3600
  CACHE__DEFAULT__SERIALIZE: true
  CACHE__DEFAULT__HOST: 127.0.0.1
  CACHE__DEFAULT__PORT: 6379
  CACHE__DEFAULT__PASSWORD:
  CACHE__DEFAULT__DB: 0
  CACHE__DEFAULT__TIMEOUT: 0
  APPLICATION__NAME: msfoole-core
  APPLICATION__VERSION: 0.0.1
  APPLICATION__DEBUG: true
  APPLICATION__MULTI__MODULE: true
  APPLICATION__DEFAULT__MODULE: Index
  APPLICATION__DEFAULT__CONTROLLER: Index
  APPLICATION__DEFAULT__ACTION: index
  APPLICATION__ALLOW__CONTROLLER: \App\COntroller\Index\Index
  APPLICATION__ALLOW__OUTPUT: success,failure,pong,hello
  APPLICATION__ACCESS__ORIGIN: http://localhost:8080
  SIDECAR__IP: 127.0.0.1
  SIDECAR__PORT: 9111
  SIDECAR__HEALTH_URI: /Index/Index/health
  SIDECAR__WHITE_LIST: *
  SIDECAR__SERVER_IP: 127.0.0.1
  SIDECAR__SERVER_PORT: 9222
  SIDECAR__CALL_IP: 127.0.0.1
  SIDECAR__CALL_PORT: 9333
  LOG__TYPE: File
  LOG__LEVEL: slow,sql,debug,info,notice,warning,error,critical,alert,emergency
  LOG__ALLOW_KEY:
  LOG__CLOSE: false
  LOG__PATH: LOG_PATH
  LOG__FILE_SIZE: 2097152
  LOG__APART_LEVEL: slow,sql,debug,info,notice,warning,error,critical,alert,emergency
  LOG__TIME_FORMAT: c
  LOG__SINGLE: false
  LOG__MAX_FILES: 100
  LOG__SLOW_TIME: 3
  LOG__DEBUG: true
  LOG__RECORD_TRACE: true
  COOKIE__PREFIX: msf_
  COOKIE__EXPIRE: 3600
  COOKIE__PATH: /
  COOKIE__DOMAIN:
  COOKIE__SECURE: false
  COOKIE__HTTPONLY:
  COOKIE__TOKEN: TOKEN
  COOKIE__AUTO_SELLING: 600
  COOKIE___CACHE_PREFIX: "user:"