name: msfoole
version: 1.0.0
description: 基于swoole的简易微服务框架
environments:
  MSFOOLE__HOST: "0.0.0.0"
  MSFOOLE__PORT: 9111
  MSFOOLE__SSL: false
  MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole-core/src/
  MSFOOLE__MONITOR__INTERVAL: 10
  MSFOOLE__SERVER__REGPORT: 9222
  MSFOOLE__SERVER__ROBOTKEY: regMachine
  MSFOOLE__CLIENT__IP: 127.0.0.1
  MSFOOLE__CLIENT__PORT: 9111
#  MSFOOLE__WEBSOCKET__KEY: 700040D41F47592C
#  MSFOOLE__WEBSOCKET__VI: 4937682F63AA8FC2
#  MSFOOLE__WEBSOCKET__SIGN: null
  MSFOOLE__CHANNEL__CAPACITY: 100
  MSFOOLE__OPTION__WORKER_NUM: 1
  MSFOOLE__OPTION__MAX_REQUEST: 10000
  MSFOOLE__OPTION__MAX_CONN: 10000
  MSFOOLE__OPTION__DAEMONIZE: false
  MSFOOLE__OPTION__LOG_LEVEL: 0
  MSFOOLE__OPTION__LOG_FILE: msfoole.log
  MSFOOLE__OPTION__REQUEST_SLOWLOG_FILE: trace.log
  MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 1
  MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 120
  MSFOOLE__OPTION__OPEN_HTTP2_PROTOCOL: false
  MSFOOLE__OPTION__RELOAD_ASYNC: false
  MSFOOLE__OPTION__ENABLE_COROUTINE: true
  MSFOOLE__OPTION__MAX_COROUTINE: 3000